### PR TITLE
Fix list command not using new prefix

### LINKED ISSUE #274: List rq/ still uses rq/ not rq\
Should be changed to follow new format

### PR DESCRIPTION
**Pull request by aekyr**
Fixes #274

### CODE REVIEW

File: src/main/java/seedu/guestnote/logic/parser/ListCommandParser.java [hunk 1]
```diff
@@ -21,22 +23,22 @@ public ListCommand parse(String args) throws ParseException {
         // Tokenize by whitespace
         String[] tokens = trimmedArgs.split("\\s+");
         long rqCount = Arrays.stream(tokens)
-                             .filter(token -> token.equalsIgnoreCase("rq/"))
+                             .filter(token -> token.equalsIgnoreCase(String.valueOf(PREFIX_REQUEST)))
```
Comment (Noob-No-1) [inline src/main/java/seedu/guestnote/logic/parser/ListCommandParser.java:26]: Great way to ensure the syntax to match required format exactly!

**Review by Noob-No-1 — COMMENTED** [review]
lgtm💥
